# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37567a3aae53fa5d0efc9fb64515acce3cca8cb2fcc6a57a0511fdca721b7f5cf77f723e99fb025173e0714672b42dd2ef1ff480ad539df94f3fcbb726508c6f

test:
  secret_key_base: 661497badda42d9b9607f6837f9d1057d408cf11abab1a950ba9f5dc79cda2907a1f1ef1319ffa069d9c291501594e333afd64f1771e80f1fc27d9b2a618d14a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
